/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appCollectionRouteRouteImport } from './routes/(app)/collection/route'
import { Route as appLibraryRouteRouteImport } from './routes/(app)/library/route'
import { Route as ProtoNewCollectionCardRouteImport } from './routes/proto/new-collection-card'
import { Route as appCollectionCollectionIdRouteImport } from './routes/(app)/collection/$collectionId'
import { Route as appLibraryIndexRouteImport } from './routes/(app)/library/index'
import { Route as appLibraryDeletedRouteImport } from './routes/(app)/library/deleted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appCollectionRouteRoute = appCollectionRouteRouteImport.update({
  id: '/(app)/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const appLibraryRouteRoute = appLibraryRouteRouteImport.update({
  id: '/(app)/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoNewCollectionCardRoute = ProtoNewCollectionCardRouteImport.update({
  id: '/proto/new-collection-card',
  path: '/proto/new-collection-card',
  getParentRoute: () => rootRouteImport,
} as any)
const appCollectionCollectionIdRoute =
  appCollectionCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => appCollectionRouteRoute,
  } as any)
const appLibraryIndexRoute = appLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLibraryRouteRoute,
} as any)
const appLibraryDeletedRoute = appLibraryDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => appLibraryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof appCollectionRouteRouteWithChildren
  '/library': typeof appLibraryRouteRouteWithChildren
  '/proto/new-collection-card': typeof ProtoNewCollectionCardRoute
  '/collection/$collectionId': typeof appCollectionCollectionIdRoute
  '/library/deleted': typeof appLibraryDeletedRoute
  '/library/': typeof appLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof appCollectionRouteRouteWithChildren
  '/proto/new-collection-card': typeof ProtoNewCollectionCardRoute
  '/collection/$collectionId': typeof appCollectionCollectionIdRoute
  '/library/deleted': typeof appLibraryDeletedRoute
  '/library': typeof appLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/collection': typeof appCollectionRouteRouteWithChildren
  '/(app)/library': typeof appLibraryRouteRouteWithChildren
  '/proto/new-collection-card': typeof ProtoNewCollectionCardRoute
  '/(app)/collection/$collectionId': typeof appCollectionCollectionIdRoute
  '/(app)/library/deleted': typeof appLibraryDeletedRoute
  '/(app)/library/': typeof appLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/library'
    | '/proto/new-collection-card'
    | '/collection/$collectionId'
    | '/library/deleted'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/proto/new-collection-card'
    | '/collection/$collectionId'
    | '/library/deleted'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/(app)/collection'
    | '/(app)/library'
    | '/proto/new-collection-card'
    | '/(app)/collection/$collectionId'
    | '/(app)/library/deleted'
    | '/(app)/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appCollectionRouteRoute: typeof appCollectionRouteRouteWithChildren
  appLibraryRouteRoute: typeof appLibraryRouteRouteWithChildren
  ProtoNewCollectionCardRoute: typeof ProtoNewCollectionCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/collection': {
      id: '/(app)/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof appCollectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/library': {
      id: '/(app)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/new-collection-card': {
      id: '/proto/new-collection-card'
      path: '/proto/new-collection-card'
      fullPath: '/proto/new-collection-card'
      preLoaderRoute: typeof ProtoNewCollectionCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/collection/$collectionId': {
      id: '/(app)/collection/$collectionId'
      path: '/$collectionId'
      fullPath: '/collection/$collectionId'
      preLoaderRoute: typeof appCollectionCollectionIdRouteImport
      parentRoute: typeof appCollectionRouteRoute
    }
    '/(app)/library/': {
      id: '/(app)/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof appLibraryIndexRouteImport
      parentRoute: typeof appLibraryRouteRoute
    }
    '/(app)/library/deleted': {
      id: '/(app)/library/deleted'
      path: '/deleted'
      fullPath: '/library/deleted'
      preLoaderRoute: typeof appLibraryDeletedRouteImport
      parentRoute: typeof appLibraryRouteRoute
    }
  }
}

interface appCollectionRouteRouteChildren {
  appCollectionCollectionIdRoute: typeof appCollectionCollectionIdRoute
}

const appCollectionRouteRouteChildren: appCollectionRouteRouteChildren = {
  appCollectionCollectionIdRoute: appCollectionCollectionIdRoute,
}

const appCollectionRouteRouteWithChildren =
  appCollectionRouteRoute._addFileChildren(appCollectionRouteRouteChildren)

interface appLibraryRouteRouteChildren {
  appLibraryDeletedRoute: typeof appLibraryDeletedRoute
  appLibraryIndexRoute: typeof appLibraryIndexRoute
}

const appLibraryRouteRouteChildren: appLibraryRouteRouteChildren = {
  appLibraryDeletedRoute: appLibraryDeletedRoute,
  appLibraryIndexRoute: appLibraryIndexRoute,
}

const appLibraryRouteRouteWithChildren = appLibraryRouteRoute._addFileChildren(
  appLibraryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appCollectionRouteRoute: appCollectionRouteRouteWithChildren,
  appLibraryRouteRoute: appLibraryRouteRouteWithChildren,
  ProtoNewCollectionCardRoute: ProtoNewCollectionCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
