/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appLibraryRouteRouteImport } from './routes/(app)/library/route'
import { Route as appLibraryIndexRouteImport } from './routes/(app)/library/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLibraryRouteRoute = appLibraryRouteRouteImport.update({
  id: '/(app)/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const appLibraryIndexRoute = appLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLibraryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof appLibraryRouteRouteWithChildren
  '/library/': typeof appLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof appLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/library': typeof appLibraryRouteRouteWithChildren
  '/(app)/library/': typeof appLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library'
  id: '__root__' | '/' | '/(app)/library' | '/(app)/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appLibraryRouteRoute: typeof appLibraryRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/library': {
      id: '/(app)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/library/': {
      id: '/(app)/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof appLibraryIndexRouteImport
      parentRoute: typeof appLibraryRouteRoute
    }
  }
}

interface appLibraryRouteRouteChildren {
  appLibraryIndexRoute: typeof appLibraryIndexRoute
}

const appLibraryRouteRouteChildren: appLibraryRouteRouteChildren = {
  appLibraryIndexRoute: appLibraryIndexRoute,
}

const appLibraryRouteRouteWithChildren = appLibraryRouteRoute._addFileChildren(
  appLibraryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appLibraryRouteRoute: appLibraryRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
